openapi: 3.0.0
info:
  title: 测试智能体自然语言接口
  description: "用于通过自然语言与测试智能体进行交互的接口"
  version: "1.0"
servers:
  - url: https://agent-connect.ai
paths:
  /agents/test/api/ask:
    post:
      summary: "askQuestion"
      description: "使用自然语言提问并获取自然语言回答，支持SSE返回"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - question
              properties:
                question:
                  type: string
                  description: "用户的自然语言问题"
                  minLength: 1
                  maxLength: 2000
                context:
                  type: object
                  description: "可选的上下文信息"
                  properties:
                    sessionId:
                      type: string
                      description: "会话ID，用于维持对话上下文"
                    userId:
                      type: string
                      description: "用户ID"
                    preferences:
                      type: object
                      description: "用户偏好设置"
      responses:
        '200':
          description: "自然语言回答，支持SSE返回"
          content:
            text/event-stream:
              schema:
                type: string
                description: "SSE流式响应"
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: "智能体的回答"
                  confidence:
                    type: number
                    minimum: 0
                    maximum: 1
                    description: "回答的置信度"
                  suggestions:
                    type: array
                    items:
                      type: string
                    description: "相关建议或推荐问题"
                  sessionId:
                    type: string
                    description: "会话ID"
        '400':
          description: "请求参数错误"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "错误信息"
                  code:
                    type: integer
                    description: "错误代码"
        '500':
          description: "服务器内部错误"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "错误信息"
  /agents/test/api/chat/history:
    get:
      summary: "getChatHistory"
      description: "获取用户的聊天历史记录"
      parameters:
        - name: sessionId
          in: query
          required: true
          schema:
            type: string
          description: "会话ID"
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: "返回记录数量限制"
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
          description: "偏移量"
      responses:
        '200':
          description: "聊天历史记录"
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: "消息ID"
                        role:
                          type: string
                          enum: ["user", "assistant"]
                          description: "消息角色"
                        content:
                          type: string
                          description: "消息内容"
                        timestamp:
                          type: string
                          format: date-time
                          description: "消息时间戳"
                  total:
                    type: integer
                    description: "总消息数量"
                  hasMore:
                    type: boolean
                    description: "是否还有更多消息"
components:
  securitySchemes:
    didwba:
      type: http
      scheme: bearer
      bearerFormat: DID-WBA
      description: "DID-WBA认证方案"
security:
  - didwba: []


